[package]
name = "token-minting-module"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
cbor = "0.11"
num-traits = "0.2"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
many = { version = "0.14", features = ["prost"] }

